language: node_js
warnings_are_errors: false
node_js:
 - "node"
after_success:
 - git config --global user.name "raglopa"
 - git config --global user.email "raglopa@gmail.com"
 - git remote rm origin
 - git remote add origin https://raglopa:${GH_TOKEN}@github.com/raglopa/flip-react.git
 - npm run deploy